### ISSUE TITLE
Making "Downloads"

### ISSUE THREAD

**Issue by ghost** [birros/web-archives#11]
Hello there. I've saved a local copy from Project Gutenberg's `.zim` file, and I would like to access its `.epub` files using my local book reader. Its webpage offers the option to "Download" it, but Web Archives doesn't seem to "download", or save, the file.

**Comment by birros** [comment]
This will require the development of a new functionality, which will take some time.

I will try to free up time next weekend to develop it, otherwise in the coming weeks, I make no promises :smile:

In the meantime, you can try to read your zim files with the [Kiwix](https://flathub.org/apps/details/org.kiwix.desktop) application, also present on Flathub, the team behind this application is the one that creates the zim files and provides the software library on which WebArchives is based. Zim files are probably better supported there.

**Comment by birros** [comment]
I just added automatic downloading of files that cannot be viewed in WebArchives.

However, the right click to download manually does not work, I could not do it quickly.

I hope it will be useful to you.
The update will arrive in about 3 hours
