### ISSUE TITLE
An option to add new websites

### ISSUE THREAD

**Issue by mlaarebi** [birros/web-archives#20]
can you add an option to add other websites? the app can analyze them bfr accepting to add them or refuse.

**Comment by birros** [comment]
Hello,

WebArchives is only a reader and not a builder of zim archives.

WebArchives only supports the zim format, this format requires a specific file tree, **there is no universal solution to package any site**. You must first use a specific script for each site, in order to make changes to its content, before you can package it.

I invite you to read this page in order to package a site: [Build your ZIM file](https://openzim.org/wiki/Build_your_ZIM_file).

Good luck!

**Comment by kelson42** [comment]
You should look at https://youzim.it, a brand new project of the Kiwix team.
