### ISSUE TITLE
How to compile on Ubuntu 14.04?

### ISSUE THREAD

**Issue by probonopd** [birros/web-archives#3]
Can you please give step-by-step instructions on how to compile web-archives on Ubuntu 14.04, the currently oldest still-supported version of Ubuntu? Thank you very much.

**Comment by birros** [comment]
Thank you for your interest, I really appreciate it.

I am so sorry but I'm not sure that WebArchives can works on it, because WebArchives uses Gtk+ features that are missing in the `3.10.8` version of Gtk+ used by Ubuntu 14.04, the flatpaked version of Gtk+ on which WebArchives development is based being `3.22.30`.

I am focusing exclusively on the Flatpak environment for the moment, until I have integrated all the features I consider essential to WebArchives.

After this phase, I will consider deploying it directly on major distributions like Ubuntu & Debian.

Sorry...

**Comment by birros** [comment]
I close this ticket knowing that flatpak is becoming a solution of choice for the installation of apps under Linux, with the appearance of an official Mozilla support for Firefox.

**Comment by probonopd** [comment]
Likewise, AppImage is becoming a solution of choice for the installation of apps under Linux, with the appearance of e.g., an official LibreOffice support for LibreOffice. Among many others.

**Comment by birros** [comment]
I agree, the choice to support only Flatpak as a deployment method is arbitrary, I assume.

This method is much simpler, flexible, easily maintainable and targets more than 20 different distributions without worrying about the specificities of each distribution.

In terms of time invested and efficiency I can hardly see any better.

Sorry 🙂
