### ISSUE TITLE
No styling for inside links

### ISSUE THREAD

**Issue by yabak123** [birros/web-archives#5]
If you search for an article then click on the article search result, the article will open fine, but if you clicked a link inside an article (the link leads to another article within the zim file) you will see the page as text only without any styling.

This issue can be found in archives like "Artificial Intelligence Stack Exchange", but this problem does not exist in "ArchWiki" archive. and the problem is existed for Ubuntu 18.04.1 LTS and Fedora 28

**Comment by birros** [comment]
I **partially fixed this bug**, at least only the part about WebArchives operation.

**There are still visual inconsistencies and dead links, but these are due to bugs in the scraper responsible for retrieving web pages and transforming them into ZIM files.**

This kind of problem is known by the team in charge of creating these files, so be patient and hope that these errors are fixed in future versions of ZIM files.

Thank you very much for your contribution ;-)
