### ISSUE TITLE
Not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by tiotrom** [birros/web-archives#6]
> tio@tio:~$ flatpak run com.github.birros.WebArchives
> Gtk-Message: 14:07:03.410: Failed to load module "unity-gtk-module"
> Gtk-Message: 14:07:03.417: Failed to load module "appmenu-gtk-module"
> Gtk-Message: 14:07:03.429: Failed to load module "unity-gtk-module"
> Gtk-Message: 14:07:03.429: Failed to load module "appmenu-gtk-module"
> 
> ** (web-archives:2): ERROR **: 14:07:03.434: server.vala:18: Could not listen on address ::1, port 32969: Error binding to address: Cannot assign requested address
>

**Comment by birros** [comment]
This bug is strange, have you tried restarting the application once or twice to see if the problem persists.

**This message indicates that the server is unable to acquire an address.**

Although the `port` is automatically chosen by the server when it starts, in order to obtain a `port` not used in principle, in practice I never encountered any problem. Maybe here `GLib` has done a bad job and that will require, in the future, coding the `port` myself in WebArchives.

**Try updating your system and Flatpak applications/runtimes before rebooting your machine to see if the problem persists.**

I tried to reproduce this bug on a new and updated installation of Ubuntu 18.04 and WebArchives (installed from Flathub) but I didn't notice any problems. I conclude that the problem depends on the state of your operating system and the changes you have made to it and not on an internal WebArchives problem.

**On the basis of this principle I am closing this issue. If the problem persists in the coming weeks, do not hesitate to report it again.**

Thank you for your return, it's really cool to see people interested in my work 😉

**Comment by tiotrom** [comment]
Ok this was because I am using a VPN with port forwarding. Without it it works. Btw I thought the app contains an offline wikipedia but I suppose I would have to download it as this program is only like a reader for such libraries, right?

**Comment by birros** [comment]
Interesting, I wouldn't have thought about that situation. I will try to support this configuration in the future, but not for now.

**And yes, the application does not integrate any content, it's necessary to download some, which can for example represent several GB for Wikipedia.**

In principle, it's possible to display a list of downloadable archives on the WebArchives home page, it may be necessary to install `gvfs` as well as the `http` backend on the host system. I am working on a feature to detect the presence of this service and suggest its installation if necessary.

Read the [README](https://github.com/birros/web-archives/blob/master/README.md) to learn how to install this service. **Archives can also be downloaded from this website in the Content only section: http://www.kiwix.org/downloads/**

**Comment by tiotrom** [comment]
Awesome. Thanks! :) Would be great to see a library of downloadable content from withing the app. Makes things much easier for people.

**Comment by birros** [comment]
Nice!

As I tried to say in the previous message, but I misspoke, **there is already a section dedicated to downloadable content on the WebArchives home page.**

Unfortunately, even if Flatpak makes things much easier for the development and deployment of an application, it is still difficult to develop an application dependent on services supposedly preinstalled on the host OS.

**I work on it to inform users when these services are missing and how to install them to take full advantage of the application.**

But making things simple is a very complicated exercise 😉

Have a nice day!
